### ISSUE TITLE
My services should list all services that the user has access to

### ISSUE THREAD

**Issue by wilzbach** [storyscript/hub#61]
Currently it's just:

![image](https://user-images.githubusercontent.com/4370550/56664927-5a2e4a00-66a9-11e9-8a93-85d24a6a228d.png)

Even though I e.g. have access to `asyncy` or `microservice`

**Comment by JeanBarriere** [comment]
Yes, there is no defined page for the account yet, so I just redirected the end user to the search page with a pre-fetched request of the microservices containing his username.

Will come soon

**Comment by JeanBarriere** [comment]
Done in #90 and improved in #91
